name: Dispatch by custom event

on:
  workflow_dispatch:
  repository_dispatch:
    types: [custom_event]

jobs:
  pipeline:
    name: Sites NextJS (Testing)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1

      - name: Set relese version
        run: |
          echo "RELEASE_VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Print env
        run: |
          printenv
