name: Inputs

on:
  workflow_dispatch:
    inputs:
      KONTENT_PROJECT_ID:
        description: "KONTENT_PROJECT_ID"
        type: string

jobs:
  pipeline:
    name: Get tag and trigger custom event pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Prepare docker image and push to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sites-prod
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
          KONTENT_PROJECT_ID: ${{ inputs.KONTENT_PROJECT_ID || 'DEFAULT' }}
        run: |
          printenv
