name: Get tag

on:
  workflow_dispatch:
    inputs:
      KONTENT_PROJECT_ID:
        description: "KONTENT_PROJECT_ID"
        type: string

jobs:
  pipeline:
    name: Get tag and trigger custom event pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set relese version
        run: |
          echo "RELEASE_VERSION=`echo ${{ ${{ inputs.KONTENT_PROJECT_ID || 'DEFAULT VALUE' }} }}`" >> $GITHUB_ENV

      - name: Print env
        run: |
          printenv
